services:
  mysql:
    image: mysql:8.0.40  # 2025年8月時点の最新安定版
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
    
  phpmyadmin:
    image: phpmyadmin:5.2.1  # 最新安定版
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
