services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: mysql
      UPLOAD_LIMIT: 128M
    depends_on:
      - mysql
    ports:
      - "8081:80"

volumes:
  mysql-data:
